### ISSUE TITLE
Gzip.gunzip throws java.util.zip.DataFormatException: invalid stored block lengths

### ISSUE THREAD

**Issue by Holmyara** [jroper/play-iteratees-extras#7]
Gzip.gunzip enumeratee throws "java.util.zip.DataFormatException: invalid stored block lengths" when I'm trying to decompress any content created by gzip command line tool. It works perfect with content produced by Gzip.gzip enumeratee but fails for any file created by gunzip.

Exception in thread "main" java.util.zip.DataFormatException: invalid stored block lengths
	at java.util.zip.Inflater.inflateBytes(Native Method)
	at java.util.zip.Inflater.inflate(Inflater.java:259)
	at play.filters.gzip.Gzip$$anon$5.play$filters$gzip$Gzip$$anon$$inflateUntilNeedsInput(Gzip.scala:235)
	at play.filters.gzip.Gzip$$anon$5$$anonfun$play$filters$gzip$Gzip$$anon$$step$2.apply(Gzip.scala:218)
	at play.filters.gzip.Gzip$$anon$5$$anonfun$play$filters$gzip$Gzip$$anon$$step$2.apply(Gzip.scala:211)

**Comment by Holmyara** [comment]
Simple test to reproduce:

val file = new File(output)
val input = new File("test2.json.gz")
val inputEnum = Enumerator.fromFile(input)
inputEnum through Gzip.gunzip() run Iteratee.foreach(ch => Unit)

**Comment by Holmyara** [comment]
"test2.json.gz" must be a file produced by gzip command line tool

**Comment by Holmyara** [comment]
I think I found what the problem with gunzip. It doesn't read bytes with file name in header. So you can produce two zip files by gzip tool: first without file name in header using -n option and second with file name in header. Gunzip throws exception when header contains original file name.
